print('='*33)
nome = (input('Digite o sue nome completo: '))
print('Em maiúsculo: ', nome.upper(), ';')
print('Em minúsculas: ', nome.lower(), ';')
separado = (nome.split())
espacos = int(nome.count(" "))
letras = len(nome)
print('Número de caracteres sem espaços', letras - espacos,';')
nome = nome.split()
print('Tamanho do primeiro nome: ', len(nome[0]))
print('='*33)